# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrain.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_1 || ORIG_REF_NAME==design_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_I2C_Reader_0_0/design_1_I2C_Reader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_I2C_Reader_0_0 || ORIG_REF_NAME==design_1_I2C_Reader_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IMU_relay_0_0/design_1_IMU_relay_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_IMU_relay_0_0 || ORIG_REF_NAME==design_1_IMU_relay_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_0_imp_xbar_0/design_1_axis_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==design_1_axis_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_0_0/design_1_axis_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_0_0 || ORIG_REF_NAME==design_1_axis_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IMU_relay_1_0/design_1_IMU_relay_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_IMU_relay_1_0 || ORIG_REF_NAME==design_1_IMU_relay_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_I2C_Reader_1_0/design_1_I2C_Reader_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_I2C_Reader_1_0 || ORIG_REF_NAME==design_1_I2C_Reader_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IMU_relay_2_0/design_1_IMU_relay_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_IMU_relay_2_0 || ORIG_REF_NAME==design_1_IMU_relay_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_I2C_Reader_2_0/design_1_I2C_Reader_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_I2C_Reader_2_0 || ORIG_REF_NAME==design_1_I2C_Reader_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_I2C_Reader_3_0/design_1_I2C_Reader_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_I2C_Reader_3_0 || ORIG_REF_NAME==design_1_I2C_Reader_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IMU_relay_3_0/design_1_IMU_relay_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_IMU_relay_3_0 || ORIG_REF_NAME==design_1_IMU_relay_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_I2C_Reader_4_0/design_1_I2C_Reader_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_I2C_Reader_4_0 || ORIG_REF_NAME==design_1_I2C_Reader_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IMU_relay_4_0/design_1_IMU_relay_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_IMU_relay_4_0 || ORIG_REF_NAME==design_1_IMU_relay_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_imp_xbar_0/design_1_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==design_1_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_1/design_1_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_0_imp_s_arb_req_suppress_concat_0/design_1_axis_interconnect_0_imp_s_arb_req_suppress_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_0_imp_s_arb_req_suppress_concat_0 || ORIG_REF_NAME==design_1_axis_interconnect_0_imp_s_arb_req_suppress_concat_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_0_imp_auto_ss_k_0/design_1_axis_interconnect_0_imp_auto_ss_k_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_0_imp_auto_ss_k_0 || ORIG_REF_NAME==design_1_axis_interconnect_0_imp_auto_ss_k_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_0_imp_auto_ss_slidr_0/design_1_axis_interconnect_0_imp_auto_ss_slidr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_0_imp_auto_ss_slidr_0 || ORIG_REF_NAME==design_1_axis_interconnect_0_imp_auto_ss_slidr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_0/design_1_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==design_1_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_1/design_1_axi_mem_intercon_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_imp_auto_pc_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_imp_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_0/design_1_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==design_1_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_2/design_1_axi_mem_intercon_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_imp_auto_pc_2 || ORIG_REF_NAME==design_1_axi_mem_intercon_imp_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_us_1/design_1_axi_mem_intercon_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_imp_auto_us_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_imp_auto_us_1} -quiet] -quiet

# XDC: c:/work/github/Care-Spine_HDL/Care-Spine/Care-Spine.gen/sources_1/bd/design_1/design_1_ooc.xdc
